### ISSUE TITLE
Openshift should provide a way to stop container gracefully

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-utils#10]
Currently when we are trying to implement openshift_stop scripts then it always send  `systemctl status openshift` in failed state because openshift process not gracefully exit. 

As per article https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/ when running our own application in a container, we must decide how the different signals will be interpreted by our app. 

```
# docker stop openshift
openshift
# docker ps -a
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                       PORTS               NAMES
a0786157a986        openshift                                 "/usr/bin/openshift s"   2 minutes ago       Exited (143) 4 seconds ago                       openshift

# docker kill --signal=SIGINT openshift
openshift
# docker ps -a
8d9d8616e791        openshift                                 "/usr/bin/openshift s"   52 seconds ago      Exited (130) 2 seconds ago                          openshift

# docker kill --signal=SIGQUIT openshift
193cad9ae9e0        openshift                                 "/usr/bin/openshift s"   42 seconds ago       Exited (2) 18 seconds ago                           openshift
```

None of above will provide a exit status 0 and it make systemd in `failed` state. There is another option `-t` which described as "Seconds to wait for stop before killing it" but I don't want to use any random waiting time.

**Comment by LalatenduMohanty** [comment]
@praveenkumar this looks like a bug from OpenShift container images. If so we should file bugs for OSE

**Comment by hferentschik** [comment]
Currently we have something like this in _openshift_stop_:

```
 docker ps | awk 'index($NF,"k8s_")==1 { print $1 }' | xargs -l -r docker rm -f -v
```

What is the indent here? Looking very fragile to me?

**Comment by praveenkumar** [comment]
@hferentschik Openshift start all containers with `k8s_` prefix and when we stop OpenShift service then those containers also need to be stopped and removed. If you have any simple way to handle it I will be happy to send PR (or better you can send PR and will add :) )

**Comment by hferentschik** [comment]
> Openshift start all containers with k8s_ prefix and when we stop OpenShift service then those containers also need to be stopped and removed

Ahh,  now I see where you are coming from. A comment would have been nice there. Is the k8s_ prefix a given? Can one really rely on it?

>  If you have any simple way to handle it I will be happy to send PR

Need to think about it, but as said now I understand where you are coming from.

**Comment by praveenkumar** [comment]
> Need to think about it, but as said now I understand where you are coming from.

https://github.com/openshift/origin/blob/master/examples/sample-app/cleanup.sh (script which I used in case you are wondering :) ).

**Comment by hferentschik** [comment]
Can this be closed now? Or is there more to be done? @praveenkumar?

**Comment by praveenkumar** [comment]
@hferentschik yes, I am going to close it now. Nothing we can do more here.
