### ISSUE TITLE
Use service name `kubernetes` instead of `k8s`  in `sccli`

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/adb-utils#102]
or support `kubernetes` as well as `k8s` in `sccli` to switch between services

**Comment by navidshaikh** [comment]
Related https://github.com/projectatomic/vagrant-service-manager/pull/190

**Comment by praveenkumar** [comment]
We implemented it `sccli.py` script. We will not going to have anything like `k8s` and going to use `kubernetes`.

**Comment by navidshaikh** [comment]
> We implemented it sccli.py script.

Which release of adb-utils and respectively of ADB is going to have this brewed?

We need make sure we update code in vagrant-service-manager to co-op with this change. 

Cc: @budhrg

**Comment by praveenkumar** [comment]
> Which release of adb-utils and respectively of ADB is going to have this brewed?

with ADB-2.1 or adb-utils 1.6 release will have it.
