### ISSUE TITLE
sccli openshift is taking more time in CDK 

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-utils#106]
Because OSE is using tag like v3.1.1.6-16 and v3.1.1.6-17 when sccli expect to be as just v3.1.1.6.  Check https://github.com/projectatomic/adb-atomic-developer-bundle/issues/342 for details.

Check below cmds. The shasum for v3.1.1.6-16 is same with cached images , so the docker pull for v3.1.1.6-16 does not happen as it is already present but I can do docker pull for v3.1.1.6-17.

```
[vagrant@rhel-cdk ~]$ docker images
REPOSITORY                                                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry.access.redhat.com/openshift3/ose                   v3.1.1.6            88178069a37f        2 weeks ago         441.9 MB
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[vagrant@rhel-cdk ~]$ docker pull registry.access.redhat.com/openshift3/ose:v3.1.1.6-16
88178069a37f: Download complete 
bf63a676257a: Download complete 
23477b5172dc: Download complete 
Status: Image is up to date for registry.access.redhat.com/openshift3/ose:v3.1.1.6-16
registry.access.redhat.com/openshift3/ose: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.

[vagrant@rhel-cdk ~]$ docker pull registry.access.redhat.com/openshift3/ose:v3.1.1.6-17
e9c4d9124920: Download complete 
95612a3264fc: Download complete 
92d4a31b3152: Download complete 
Status: Downloaded newer image for registry.access.redhat.com/openshift3/ose:v3.1.1.6-17
registry.access.redhat.com/openshift3/ose: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
```

OSE tags are as below. https://registry.access.redhat.com/v1/repositories/openshift3/ose/tags

{
"latest": "e9c4d91249206195e012c51a85fd47a31b6f0d2364af4c4c3736b5f5e2ecd57a", "v3.1.0.4": "62208f15133798af253a651386ae2753da9130fcc68f1863cbd735c547356173", "v3.1.0.4-1": "2eb816e9a7d05f6d5816be42ba21cf272770a9be1d15e839e7474c0541a40bc7", "v3.1.0.4-2": "d4caa301790ed1c64e2b219d82839f6ee5b4dcf3902c2f9e677b4643255e59a9", "v3.1.0.4-3": "62208f15133798af253a651386ae2753da9130fcc68f1863cbd735c547356173", "v3.1.1.6": "e9c4d91249206195e012c51a85fd47a31b6f0d2364af4c4c3736b5f5e2ecd57a", "v3.1.1.6-10": "b9797469249dcae21e0ee09e9ce57ea4b243515f6022acaaed2fb1151a2b78c4", "v3.1.1.6-12": "fdb14d058b48fb0bb35a02d8bec596b974eae51cec864311d2686fd23335ef5b", "v3.1.1.6-14": "37824d3edc2e2549bfdd1e96e143d4bdd36bd6b0332004d9444afc8f9072c20d", "v3.1.1.6-15": "f69933b7fc281c95974b2af80fcf05ceb7e5e7717c16657a271048f430826353", "v3.1.1.6-16": "88178069a37f78271c153243521cc5c11fd96bcda2ce7bdedd458b4b50ce5115", "v3.1.1.6-17": "e9c4d91249206195e012c51a85fd47a31b6f0d2364af4c4c3736b5f5e2ecd57a", "v3.1.1.6-3": "f489edbeb9a70ced0065e7610fbdfa94929f132331fc63d656da951ddd36ba15"}

**Comment by praveenkumar** [comment]
@LalatenduMohanty I can see 2 different way to tackle it in `sccli`.
1. Parse box variant and see if it is CDK or ADB and then take required action like in case of CDK we will not going to pull.
2. Check if tag is exit before pulling it using `docker images -q <image_name>` and it will only check locally if image with tag is available then not pull. 

I honestly think before we implement we should have a conversation with openshift guys to understand their image update process upstream/downstream.

**Comment by aweiteka** [comment]
```
$ time vagrant up
...
real    23m18.004s
user    0m15.688s
sys 0m12.239s
```

This is a huge blocker to new users. Many would have long given up.

**Comment by praveenkumar** [comment]
@aweiteka yes, agreed but in case of CDK we disabled it for our GA. I think you tried a ADB box where we don't have image cache.

**Comment by LalatenduMohanty** [comment]
@praveenkumar WRT https://github.com/projectatomic/adb-utils/issues/106#issuecomment-215633657 I agree. 
@aweiteka for CDK it should take less than 2 minutes as we have the OpenShift images cached in the Vagrant box

**Comment by LalatenduMohanty** [comment]
@praveenkumar is  this issue still relevant?

**Comment by praveenkumar** [comment]
It is not relevant and we fixed it already for CDK.
