### ISSUE TITLE
Missing OpenShift templates

### ISSUE THREAD

**Issue by tnozicka** [projectatomic/adb-utils#111]
There is a lot of missing OpenShift templates in ADB. I am personally missing Jenkins which used to be there in persistent and ephemeral version.

References:
- https://docs.openshift.org/latest/install_config/imagestreams_templates.html
- https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples
- https://github.com/openshift/origin/tree/master/examples

Listing templates:

``` bash
oc get templates -n openshift
```

Here is an overview of templates that are in OpenShift Online v3 Developer preview:

```
cakephp-example
cakephp-mysql-example
dancer-example
dancer-mysql-example
django-psql-example
eap64-https-s2i
eap64-mongodb-persistent-s2i
eap64-mysql-persistent-s2i
eap64-postgresql-persistent-s2i
jenkins-persistent
jws30-tomcat7-https-s2i
jws30-tomcat7-mongodb-persistent-s2i
jws30-tomcat7-mysql-persistent-s2i
jws30-tomcat7-postgresql-persistent-s2i
jws30-tomcat8-https-s2i
jws30-tomcat8-mongodb-persistent-s2i
jws30-tomcat8-mysql-persistent-s2i
jws30-tomcat8-postgresql-persistent-s2i
mongodb-persistent
mysql-persistent
nodejs-mongodb-example
postgresql-persistent
rails-postgresql-example
```

**Comment by praveenkumar** [comment]
@tnozicka We had a discussion about what templates to include for openshift_provision and that was the decision we took after different suggestions https://github.com/projectatomic/adb-utils/issues/13

**Comment by tnozicka** [comment]
@praveenkumar I briefly read the discussion and I understand why we don't want to have a lot of templates although this might be reevaluated since there wasn't OpenShift Online v3 before to guide this effort. But it is more of a product man. decision.

@praveenkumar But Jenkins template is a must. OpenShift origin already has support for syncing builds with Jenkins and it is how CI/CD workflow is going to work for OpenShift.

**Comment by tnozicka** [comment]
To cite the docs[1]:

> You can populate your OpenShift installation with useful sets of Red Hat-provided image streams and templates to make it easy for developers to create new applications. By default, the advanced installation method automatically creates these sets in the openshift project, which is a default project to which all users have view access.

I would really like to see the default templates in ADB. One reason why developers use ADB is that it contains pre-configured OpenShift environment. But right from the start they find out that the default templates which are installed BY DEFAULT with advanced installation and are present in OpenShift v3 Online are missing. Adding those templates is one of the steps to better user experience.

I will work on PR at least for Jenkins until this is decided.

**Comment by LalatenduMohanty** [comment]
+1 for Jenkins. I think it is time we put some logic in the code to to export extra or different templates for ADB VS CDK

**Comment by praveenkumar** [comment]
@LalatenduMohanty you mean for CDK we should not use those templates? Also we are caching those template in our repo which need to be updated time to time so that those templates works with new release also.

**Comment by LalatenduMohanty** [comment]
@praveenkumar We can, if it makes sense for CDK use case. But we should have the flexibility to choose. 

> Also we are caching those template in our repo which need to be updated time to time so that those templates works with new release also.

Yes, I think it should be part of a script which we run time to time during releases.
