### ISSUE TITLE
Allow a basic user to access the route of the registry

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-utils#113]
The CDK exposes the OpenShift registry as a external route. There is a need from tooling to "know" the exposed route in order to push images to it. See - https://issues.jboss.org/browse/JBIDE-22314

Unfortunately,  the openshift-dev user cannot view routes in the default project (`oc get routes`)

There are two basic approaches:
- Add some additional privileges to openshift-dev (and all basic-users). Something like _cluster-readers_. This might be useful for other things as well. On the down side the permissions might be to wide as well.
- Add something to service-manager plugin, for example add another variable to _vagrant service-manager env openshift [--script-readable]_. This would solve the particular need to "knowing" just the registry route. 

In the latter case, we probably want to move the issue to the vagrant-service-manager plugin.

**Comment by praveenkumar** [comment]
@hferentschik my vote is to implement  both approaches :)

**Comment by jcantrill** [comment]
@smarterclayton Way back when the world was young we merged this proposal https://github.com/openshift/origin/commits/master/docs/proposals/capabilities.md out of the need for clients like JBT to discover data about the server.  What is the recommended approach for pushing images to the cluster registry.  Annotating a route with a well known annotation could be an option other then their is no way for a non-admin user to find that route.  Aside from the policy and permission concerns, how does tooling discover useful services?

**Comment by hferentschik** [comment]
> my vote is to implement both approaches :)

fair enough. I guess both seems reasonable. Also adding another field to the openshift env call seem to be quite straight forward and generally useful.

**Comment by hferentschik** [comment]
+1 for merging
