### ISSUE TITLE
Enable Landrush as the default DNS solution

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-utils#128]

**Comment by praveenkumar** [comment]
@hferentschik Are we good to add it for our CDK/ADB boxes now?

**Comment by hferentschik** [comment]
Thinking about it, I'd refer to wait for Landrush 1.1.0 which will also automate the setup of DNS on Windows (opposed to having to manually add the DNS server 127.0.0.1 to the network connection). Right now we have a zero conf solution, with Landrush 1.0.0 we are asking for manual intervention. At the very least I would like to get some feedback from product owners on this one.

Also, it is essential that we test Landrush properly on the various platforms. @mmalina any idea who would b looking into testing Landrush on the various platforms?

**Comment by mmalina** [comment]
@hferentschik since this will be part of CDK, I believe Ondrej Ptak or his CDK QE team mates are the ones you should contact about this.

**Comment by LalatenduMohanty** [comment]
@hferentschik is it still an issue? We have already integrated Landrush in ADB.

**Comment by hferentschik** [comment]
Hmm, I guess for the CDK we can create a new issue. Also it seems odd to have the issue in adb-utils anyways. Closing it.
