### ISSUE TITLE
OpenShift templates should be packaged and available from stock Vagrantbox

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-utils#13]
This help to address the issue where an application developer should be able setup OpenShift in CDK/ADB and run one template without connecting to internet.

**Comment by LalatenduMohanty** [comment]
As discussed with @praveenkumar we can use https://github.com/openshift/nodejs-ex for the purpose

**Comment by LalatenduMohanty** [comment]
As discussed in the container-tools here are the templates we are planning to include

> 1) EAP + MySQL
> 2) EWS + MySQL
> 3) NodeJS + Mongo
> 4) LAMP

**Comment by praveenkumar** [comment]
As per ML discussion https://www.redhat.com/archives/container-tools/2016-February/msg00085.html , below templates should be part of OpenShift. 

1) eap64-mysql-persistent-s2i
2) jws30-tomcat7-mysql-persistent-s2i
3) nodejs-mongodb-example
4) cakephp-mysql-example

**Comment by LalatenduMohanty** [comment]
These are the github links we got
1) https://github.com/jboss-openshift/application-templates/blob/master/eap/eap64-mysql-persistent-s2i.json
2) https://github.com/jboss-openshift/application-templates/blob/master/webserver/jws30-tomcat7-mysql-persistent-s2i.json
3) https://github.com/openshift/nodejs-ex
4) https://github.com/openshift/cakephp-example

**Comment by LalatenduMohanty** [comment]
With https://github.com/openshift/cakephp-example I am not able to find the templates. May be I am missing something CC @praveenkumar @hferentschik

**Comment by hferentschik** [comment]
> With https://github.com/openshift/cakephp-example I am not able to find the templates. May be I am missing something

@LalatenduMohanty did you figure this out. I have not checked, but will have a look later today or tomorrow.

**Comment by praveenkumar** [comment]
> With https://github.com/openshift/cakephp-example I am not able to find the templates. May be I am missing something CC @praveenkumar @hferentschik

Current repo is for openshift v2 (as per readme it still uses `rhc`), hope it have different github url for openshift v3. https://github.com/openshift/cakephp-ex is what we need.
