### ISSUE TITLE
Should ADB be using CentOS based ImageStreams over RHEL based ones when available?

### ISSUE THREAD

**Issue by tnozicka** [projectatomic/adb-utils#136]
Looking at `adb-utils/services/openshift/templates/image-streams-rhel7.json` we are using ImageStream `jenkins` based on image `registry.access.redhat.com/openshift3/jenkins-1-rhel7:latest`. But there is also an image `docker.io/openshift/jenkins-1-centos7`.

(And e.g. `docker.io/openshift/jenkins-1-centos7:dev` has a some very important new features. So the ImageStreams are not equivalent.)

One of the ImageStreams definitely needs to stay named `jenkins` because of other dependencies.
What should we do in such a case?
1. provide only CentOS version in ADB and CDK would provide RHEL based one
2. suffix RHEL based IS
3. another combination

I am more inclined to option 1. The only inconsistency is that we cannot do this for all RHEL based images because most probably some of them don't have matching counterparts in CentOS.

cc: @LalatenduMohanty

**Comment by LalatenduMohanty** [comment]
@tnozicka technically we can achieve option 1 or 2 . Before deciding I have some questions on them.

Do the advancements in docker.io/openshift/jenkins-1-centos7:dev will comedown to RHEL based Jenkins in future? if so we can easily choose option1.

**Comment by tnozicka** [comment]
> Does the advancements in docker.io/openshift/jenkins-1-centos7:dev will comedown to RHEL based Jenkins in future? if so we can easily choose option1.

@LalatenduMohanty Yes, it should be in RHEL version once it's done.

**Comment by LalatenduMohanty** [comment]
@tnozicka cool, then it makes sense to go for option 1 as ADB is upstream and it can take more cutting edge feature from respective upstream projects where ever applicable.

**Comment by tnozicka** [comment]
@LalatenduMohanty To make sure:
Will we replace RHEL IS with CentOS ones in ADB wherever it has CentOS alternative and leave RHEL IS when there is no alternative?

**Comment by LalatenduMohanty** [comment]
@tnozicka We should use the Jenkins based on CentOS for ADB and Jenkins based on RHEL for CDK. /etc/os-release in the ADB/CDK box have information about whether it is CDK or ADB.

**Comment by tnozicka** [comment]
@LalatenduMohanty I agree.

But I opened this issue to be more general than Jenkins. Should this be considered a general rule when CentOS and RHEL IS collide in ADB?

**Comment by LalatenduMohanty** [comment]
@tnozicka yes. However we should be careful in not creating very disjoint experiences between ADB vs CDK.

**Comment by tnozicka** [comment]
@LalatenduMohanty Ok, I will send PR shortly.
