### ISSUE TITLE
openshift_option uses a hard coded IP

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-utils#14]
ATM, the default host is hard-coded:    

OPTIONS="-r adb.vm -host 10.1.2.2"

This ties the VM to a specific IP. This should really be a determined IP. Or maybe we can get it to work w/o!?

**Comment by praveenkumar** [comment]
> This ties the VM to a specific IP. This should really be a determined IP. Or maybe we can get it to work w/o!

Yes, I was going to file this issue, determining VM ip is bit tricky but can be done like adbinfo plugin is doing, I have to try it out. `w/o` you mean loopback device?

**Comment by hferentschik** [comment]
No, not loopback device, but just hostname without IP.

**Comment by praveenkumar** [comment]
> No, not loopback device, but just hostname without IP. 

Ah, I have to test it out if that works. I will update after testing it.

**Comment by hferentschik** [comment]
This assumes that DNS works, but either solution Landrush or xip.io should work. Not sure whether this would have any other drawback. Also need to verify all usages of the IP and see whether we get away without it. Would be kind of nice anyways to address the instance via cdk.dev:8443 instead of the more cryptic 10.1.2.2:8443.
