### ISSUE TITLE
Release 1.8.0

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-utils#140]
It has been two weeks from last release and we should release a new one soon. Also we have PRs from @tnozicka merged.

**Comment by praveenkumar** [comment]
@LalatenduMohanty yes, will do that soon.

**Comment by tnozicka** [comment]
@praveenkumar please, wait with the release for one small PR. I will send it momentarily.

**Comment by tnozicka** [comment]
@praveenkumar this one: https://github.com/projectatomic/adb-utils/pull/143

**Comment by praveenkumar** [comment]
Scratch build : https://cbs.centos.org/koji/taskinfo?taskID=96032

To test with current vagrant file of ose make below modification.

```
  config.vm.provision "shell", run: "always", inline: <<-SHELL
    sudo yum install -y http://cbs.centos.org/kojifiles/work/tasks/6033/96033/adb-utils-1.8-1.el7.noarch.rpm
    sudo DOCKER_REGISTRY=#{DOCKER_REGISTRY} IMAGE_TAG=#{IMAGE_TAG} IMAGE_NAME=#{IMAGE_NAME} /usr/bin/sccli openshift
  SHELL
```

**Comment by tnozicka** [comment]
Checked:
- Jenkins ImageStreams + Templates
- Running latest OpenShift
- Running Jenkins
- Building image and pushing to internal registry

@praveenkumar LGMT

**Comment by praveenkumar** [comment]
Tagged build: https://cbs.centos.org/koji/taskinfo?taskID=96034 and released
