### ISSUE TITLE
Support OpenShift metrics in ADB

### ISSUE THREAD

**Issue by tnozicka** [projectatomic/adb-utils#152]
Latest OpenShift console requires **metrics** running in your OpenShift cluster to display CPU load, ...

OpenShift has added `--metrics` flag to `oc cluster` command to support it.

I have found the merge, I think https://github.com/openshift/origin/pull/9310/files

@praveenkumar  you can consult with @csrwng how to do the same in ADB and it's provisioning.

CC: @ALRubinger

**Comment by tnozicka** [comment]
https://github.com/openshift/origin-metrics

**Comment by jorgemoralespou** [comment]
[This](https://github.com/openshift-evangelists/vagrant-origin/blob/11c3be8d8e9dda7f574f7322b7b4f7339528baa9/scripts/base/addons-setup#L87-L123) is how we install metrics, and it's working as well, and maybe easier to understand/port.

**Comment by praveenkumar** [comment]
@jorgemoralespou yes we already have PR for same and tested by @tnozicka but we have some ideas to make it part of addons and need some base code refactoring.
