### ISSUE TITLE
sccli should output the status of service like systemctl

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/adb-utils#154]
Usually, systemctl displays process states with ID and other information as below:

```
$ vagrant ssh -c "sudo systemctl status docker"
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Fri 2016-06-17 21:55:06 EDT; 9min ago
     Docs: http://docs.docker.com
 Main PID: 3441 (code=killed, signal=TERM)
....
```

Where `sccli` only provide exit code as:

```
$ vagrant ssh -c "sudo sccli docker status"       
Connection to 127.0.0.1 closed.

$ echo $?
3
```

It would be great if at least we get information like `Active` and `Main PID` while running `sccli docker status`.

**Comment by praveenkumar** [comment]
> It would be great if at least we get information like Active and Main PID while running sccli docker status.

I didn't understand the usecase for it. If you are using sccli for services then exit status will tell you about service status which you can use programmatic.  

```
# vagrant ssh -c "sudo systemctl status docker"
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─http-proxy.conf
   Active: active (running) since Wed 2016-06-22 02:01:42 EDT; 7min ago
     Docs: http://docs.docker.com
  Process: 14585 ExecStartPre=/opt/adb/cert-gen.sh (code=exited, status=0/SUCCESS)
 Main PID: 14587 (sh)
   Memory: 254.7M
...
# echo $?
0

# vagrant ssh -c "sudo sccli docker status"
Connection to 192.168.121.222 closed.

# echo $?
0  => Same as systemctl status
```

**Comment by brgnepal** [comment]
This will be used in acceptance tests to verify service is stop and started.

If you found this as not real use case for customer, please feel free to close it.

Current implementation of acceptance tests heavily use [status output](https://github.com/projectatomic/vagrant-service-manager/blob/master/features/support/env.rb#L100) and having hard time migrating it based on `new sccli` change.

**Comment by praveenkumar** [comment]
@budhrg How about https://github.com/projectatomic/vagrant-service-manager/blob/master/features/support/env.rb#L106 only rely on the exit_code because in Unix exit code is proper way to find a process status?

**Comment by praveenkumar** [comment]
@budhrg you have any other discussion for this issue or should I close it?

**Comment by brgnepal** [comment]
Closing it as I will try to implement based on the exit code.
