### ISSUE TITLE
Changing OPENSHIFT_SUBDOMAIN in /etc/sysconfig/openshift_option is w/o effect

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-utils#155]
It used to be possible to do something like this in the _Vagrantfile_

```
    cdk.vm.provision :shell, inline: <<-SHELL
      sed -i.orig -e "s/OPENSHIFT_SUBDOMAIN=.*/OPENSHIFT_SUBDOMAIN='#{tld}'/g" /etc/sysconfig/openshift_option
    SHELL
```

Even though it is still possible and OPENSHIFT_SUBDOMAIN gets successfully installed, the default of xip.io is used in `/var/lib/openshift/openshift.local.config/master/master-config.yaml`. 

Is there another way to configure the domain now or why does changing this option not work anymore.

**Comment by praveenkumar** [comment]
@hferentschik I am not sure if you performed `vagrant up` or `vagrant provision` after adding this shell provision script. I tried it in a clean setup and it does create entry for sub-domain for `master-config.yaml`. 

```
[prkumar@dhcp193-119 base_cdk]$ tail -n +66 Vagrantfile 
  config.vm.provision :shell, inline: <<-SHELL
    sed -i.orig -e "s/OPENSHIFT_SUBDOMAIN=.*/OPENSHIFT_SUBDOMAIN='#{tld}'/g" /etc/sysconfig/openshift_option
  SHELL

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    systemctl enable openshift 2>&1
    systemctl start openshift
  SHELL

[vagrant@rhel-cdk ~]$ cat /etc/sysconfig/openshift_option
# /etc/sysconfig/openshift_options

# Modify these options if you want to change openshift hostname
OPENSHIFT_SUBDOMAIN='cdk.vm'
IMAGE="registry.access.redhat.com/openshift3/ose:v3.2.0.44"

[vagrant@rhel-cdk ~]$ grep cdk /var/lib/openshift/openshift.local.config/master/master-config.yaml
  subdomain: cdk.vm

[vagrant@rhel-cdk ~]$ grep xip /var/lib/openshift/openshift.local.config/master/master-config.yaml
[vagrant@rhel-cdk ~]$ 
```

**Comment by hferentschik** [comment]
@praveenkumar But you are using _systemctl_ as well? Is this required? I guess the restart forces the _openshift_option_ to be re-read. Is this the way to do it? I thought we are going away from _systemctl_!?

**Comment by praveenkumar** [comment]
> I thought we are going away from systemctl!?

Why we are going away with systemctl? I think that is the only way currently we have to run openshift.

> I guess the restart forces the openshift_option to be re-read. Is this the way to do it? 

you mean `systemctl restart openshift`? Even that doesn't going to work out because of https://github.com/projectatomic/adb-utils/blob/master/services/openshift/scripts/openshift#L76-L105 block and we need a way to move out some of configuration which should reflect each changes.

**Comment by hferentschik** [comment]
> Why we are going away with systemctl? I think that is the only way currently we have to run openshift.

Are we not using `config.servicemanager.services` to control what gets started (which under the hood uses sccli & systemctl). AFAIU we had _systemctl_ left in the CDK 2 Vagrant setup, because there was the problem with additional images getting pulled.

```
config.servicemanager.services = "docker"

config.vm.provision "shell", run: "always", inline: <<-SHELL
  systemctl enable openshift 2>&1
  systemctl start openshift
SHELL
```

My understanding is that the above is a workaround. the shell provisioning should not be needed anymore and if one wants to use OpenShift, one does not even have to use
`config.servicemanager.services` since it is the default (at least with the CDK).

Do we agree so far?

So this begs the question how one then as part of this process changes the Docker/Openshift options to for example add other unsecured registries or in this particular case change the default TLD. It's almost we need some additional `config.servicemanager.xyz` properties to control these options.

**Comment by praveenkumar** [comment]
> Do we agree so far?

Yes agreed.

> So this begs the question how one then as part of this process changes the Docker/Openshift options to for example add other unsecured registries or in this particular case change the default TLD. 

Usually when someone try to change config for a service it need restart to make sure those changes can be part of the service. In case of unsecured registry it suppose to added to docker config file and docker restart needed and for TLD change happen from OpenShift side and again reboot needed for change.

**Comment by hferentschik** [comment]
> reboot needed for change.

Reboot via _systemctl_ or via _sccli_? Personally, I find this week. It might be what we have to do now, but I'd rather be able to set the right properties and let it be picked up by the service-manager.

**Comment by praveenkumar** [comment]
> Reboot via systemctl or via sccli?

`sccli` use `systemctl` in the backgroud so when we execute `sccli openshift restart` in the backgroud `systemctl restart openshift` execute.

**Comment by hferentschik** [comment]
> sccli use systemctl in the backgroud so when we execute sccli openshift restart in the backgroud systemctl restart openshift execute.

sure, but what is the message we want to give the user? sccli or systemctl? AFAIR we said the user should use sccli.

**Comment by praveenkumar** [comment]
> sure, but what is the message we want to give the user?

we want user to use VSM which internally use sccli. we are not telling user to use `sccli` explicitly and also we didn't put any documentation for it (ADB/CDK) side. 

So user have 2 option to make config changes :- 
1. Add changes to vagrantfile and then do `vagrant up` and this case changes auto picked by configuration and applied.
2. `vagrant ssh` and in the box edit config file and try to restart service which should make sure it will update configuration as required (currently for openshift we need some modification so that this option works)

**Comment by hferentschik** [comment]
> Add changes to vagrantfile and then do vagrant up and this case changes auto picked by configuration and applied.

I am lost, this is what I am trying to do and obviously this is not working w/o a restart. Option 2 is also bad, since I have to do that each single time I destroy and recreate the VM. 

> we want user to use VSM which internally use sccli.

Cool me too. But that means we are missing a piece, right? Since how am I going to use the service-manager if I need to make changes to the Docker/Openshift options. We need a way to pass this to the service-manager which needs to apply them, prior the start of Docker/OpenShift. Or am I missing something.

**Comment by hferentschik** [comment]
> vagrant ssh and in the box edit config file 

So now I am wondering, which config file do you mean? You mean _master-config.yaml_? So are you saying that once the VM has started, changing _openshift_option_ is w/o effect? Then we for sure have a bug here.

BTW, I also tried 

```
    cdk.vm.provision :shell, inline: <<-SHELL
      sed -i.orig -e "s/OPENSHIFT_SUBDOMAIN=.*/OPENSHIFT_SUBDOMAIN='#{tld}'/g" /etc/sysconfig/openshift_option
      systemctl restart openshift
    SHELL
```

Without success.

**Comment by praveenkumar** [comment]
> So now I am wondering, which config file do you mean? You mean master-config.yaml? So are you saying that once the VM has started, changing openshift_option is w/o effect? Then we for sure have a bug here.

Yes, we do have bug because restart doesn't change which daemon is looking for.

> Without success.

Again, if you added that snip after openshift service start it will not work. I am going to send a patch for this.

**Comment by praveenkumar** [comment]
@hferentschik Above patch will enable that setting but we have to keep in mind if a user already deployed some app using older sub-domain and then change the domaine and deployed other apps then older deployed app route is going to associated with older sub-domain.

```
$ oc get route 
NAME              HOST/PORT                                                PATH      SERVICE           TERMINATION   LABELS
cakephp-example   cakephp-example-sample-project.rhel-cdk.vm                         cakephp-example                 app=cakephp-example,template=cakephp-example
nodejs-example    nodejs-example-sample-project.rhel-cdk.10.1.2.2.xip.io             nodejs-example                  app=nodejs-example,template=nodejs-example
```

**Comment by hferentschik** [comment]
> Above patch will enable that setting

cool

> but we have to keep in mind if a user already deployed some app using older sub-domain and then change the domaine and deployed other apps then older deployed app route is going to associated with older sub-domain.

Sure. But that is not problem really. These are just routes which can easily be changed. Also, they will actually still work. Nothing wrong with the routes. The sub domain value just provides the default.
