### ISSUE TITLE
Exposing OpenShift registry via a route also requires adjusting of the Docker daemon options

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-utils#17]
To expose the OpenShift registry the current provisioning is doting something like

```
oc expose service docker-registry --hostname ${registry_host_name}
```

This won't really help much without also editing the Docker daemon options and adding `registry_host_name` to the list of insecure registries. See also https://github.com/redhat-developer-tooling/openshift-vagrant/blob/master/cdk-v2/scripts/configure_docker.sh#L39

**Comment by praveenkumar** [comment]
This is fixed now.
