### ISSUE TITLE
Vagrantfile unable to pick Proxy environment variable dynamically  

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/adb-utils#173]
Vagrantfile unable to pick Proxy environment variable dynamically  

There is no checks in Vagrantfile to read environment variable for proxy and use it for further Proxy settings. As a result the vm traffic is not going through proxy. 
Discussed with @LalatenduMohanty , @budhrg . 
File link : https://gist.github.com/naina-verma/106183d6ce7a742d91ed1acc1eda7745
from line 34-36 there should be check for ENV variables

**Comment by LalatenduMohanty** [comment]
This might be duplicate of https://github.com/projectatomic/adb-atomic-developer-bundle/issues/488. Though both are different issues but the solution might be one.

**Comment by LalatenduMohanty** [comment]
Closing the issue as it is tracked in https://github.com/projectatomic/adb-atomic-developer-bundle/issues/488
