### ISSUE TITLE
Capability to have run different tag of openshift on CDK

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-utils#185]
Currently what CDK have is only a specific version of openshift and it's a bottleneck when user want to tryout a newly available version/tag of openshift.

**Comment by LalatenduMohanty** [comment]
ADB users can modify the tag in the Vagrantfile and subsequent vagrant up will download the Origin docker images and set it up, we should allow CDK users to do same for OCP versions.

**Comment by hferentschik** [comment]
The question is whether we really want this? I agree it sounds nice, but at the same time it also means they are using something untested. At the very least this needs to be made clear. It's a two-edged sword really.

**Comment by praveenkumar** [comment]
@hferentschik yes agree, @LalatenduMohanty do we have approval for it because in past we saw stuff breaking when we moved with 1.1 to 1.2 OSP.

**Comment by LalatenduMohanty** [comment]
@praveenkumar @hferentschik It seems users want to have new version of OCP (even for minor version upgrades 3.2.x to 3.2.y) as soon as possible along with new versions, we should add this functionality. But we will continue with the way we do the caching and releases and it would be the supported OCP version in CDK.
This will also enable us to test the pre-release versions of OCP in CDK through automation.
