### ISSUE TITLE
Do local check for available cached images.

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-utils#190]
Currently we enabled `docker pull` for ADB/CDK which make startup process little slow because even a image cached then docker will get metadata over internet to validate the image and in case of openshift, we do sure that if something changes then they create new tag and not update the existing tags. Keep those in front we can have a validation flag in front of docker pull which will make sure only new tag images get pulled otherwise continue to use cached images.

One way is to use `"$(docker images -q myimage:mytag 2> /dev/null)" == ""` script as placeholder for this flag.

@LalatenduMohanty @hferentschik @budhrg  comments?

**Comment by LalatenduMohanty** [comment]
@praveenkumar +1, we should do that to make sure user experience does not take a dip.  But I am not aware of the logic behind why same tags are reused for new builds. That's something we tried to get an answer  in the past isn't it?

**Comment by praveenkumar** [comment]
>  But I am not aware of the logic behind why same tags are reused for new builds. That's something we tried to get an answer in the past isn't it?

We got the answer I think when @hferentschik ask to openshift team and they made sure in future they will do proper tagging.
