### ISSUE TITLE
Only restart docker if needed

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/adb-utils#24]
We shouldn't be restarting docker [here](https://github.com/projectatomic/adb-utils/blob/cfc3e8d14136a4bb7a9fc4b079a8d2847838df28/services/openshift/scripts/docker_config#L32) unless we really need to.

**Comment by hferentschik** [comment]
+1 and while on it fix the related issues #28 and #29

**Comment by LalatenduMohanty** [comment]
@dustymabe @hferentschik you mean the docker restart we are doing [here](https://github.com/projectatomic/adb-utils/blob/cfc3e8d14136a4bb7a9fc4b079a8d2847838df28/services/openshift/scripts/docker_config#L32) is not necessary? I thought otherwise

**Comment by LalatenduMohanty** [comment]
Got it. We should put a condition to check if /etc/sysconfig/docker has changed then restart the docker service. As OpenShift service start will call the script every time.  

```
sed -i.back "/# INSECURE_REGISTRY=*/c\INSECURE_REGISTRY=\"--insecure-registry 172.30.0.0/16 --insecure-registry $ip\"/" /etc/sysconfig/docker
systemctl restart docker
```
