### ISSUE TITLE
/opt/adb/openshift/docker_config should allow to append multiple insecure registries

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-utils#29]
The script should allow to be called multiple times specifying new registries to add. This way it could also be called from the `Vagrantfile` during provisioning in order to add for example hub.cdk.10.1.2.2.xip.io (the external route for the OpenShift registry).

For this to work one needs to be able to specify a host or IP. The script seems to only deal with IPs. Also it should check the `INSECURE_REGISTRY` option whether the registry to add is already added. If so, do nothing, if not add.

Also the current `sed` expression seems wrong, resulting in a trailing '\':

```
INSECURE_REGISTRY="--insecure-registry 172.30.0.0/16 --insecure-registry 10.1.2.2"/
```

**Comment by hferentschik** [comment]
In the current setup I cannot change the `INSECURE_REGISTRY` via provisioning in the `Vagrantfile`, since the OpenShift service configuration will override changes to this variable. It really need to be a append solution, instead of replacing the whole line.

**Comment by LalatenduMohanty** [comment]
Closing the issue as PR is merged now

**Comment by hferentschik** [comment]
ok, works for CDK Beta5 now.
