### ISSUE TITLE
The OpenShift service creates an OpenShift instance with no authentication 

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-utils#3]
_From @hferentschik on January 25, 2016 13:48_

I think is it not good practice to use an unauthenticated OpenShift. This is of course open for discussion, but I think one should at least use basic authentication.

One needs to also discuss whether an admin user should be pre-created.

_Copied from original issue: projectatomic/adb-atomic-developer-bundle#215_

**Comment by praveenkumar** [comment]
_From @hferentschik on January 25, 2016 13:48_

Please add focus:devex

**Comment by hferentschik** [comment]
Simplest would be to use HTPasswd backed authentication - https://docs.openshift.com/enterprise/3.0/admin_guide/configuring_authentication.html#HTPasswdPasswordIdentityProvider

**Comment by hferentschik** [comment]
We need to get _htpasswd_ installed on the box though.

**Comment by hferentschik** [comment]
I think this once can be closed now.

**Comment by praveenkumar** [comment]
This is already fixed.
