### ISSUE TITLE
/var/lib/openshift should be used as base directory of OpenShift

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-utils#30]
Currently /var/lib/origin is used, even though all other scripts use just 'openshift'.

Maybe we should even put it under `/opt/adb/openshift`!?

**Comment by LalatenduMohanty** [comment]
yeah , we even use `/var/lib/origin` even in CDK.

**Comment by LalatenduMohanty** [comment]
@hferentschik This issue does not look like for a 2.0 GA. Let me know your thoughts

**Comment by hferentschik** [comment]
Sure why not. It is such a simple change. But yes, it is not a blocker.

**Comment by praveenkumar** [comment]
> Maybe we should even put it under /opt/adb/openshift!?

This directory we are using as service scripts base. I prefer `/var/lib/openshift` and as you said it easy fix.

**Comment by hferentschik** [comment]
Either way. As long as we get away from _origin_ and use something more universally valid like _openshift_.  _var/lib/openshift_ works for me_

**Comment by praveenkumar** [comment]
I am reopening this issue because it need more work, we also have to overwrite workdir and kubconfig env before starting openshift container otherwise it will fail.

**Comment by LalatenduMohanty** [comment]
@praveenkumar maybe we want to revert the patch too? then have a complete PR later

**Comment by praveenkumar** [comment]
This is now fixed with latest patch.
