### ISSUE TITLE
Admin user does not have system:admin privileges 

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-utils#32]
```
$ oc get nodes
 Error from server: User "admin" cannot list all nodes in the cluster
```

I would have expected the admin user can do that!?

**Comment by LalatenduMohanty** [comment]
@hferentschik `admin` is cluster-admin in this case and we create them as below. Need to dig more to understand what is its privileges. I am sure you can suggest the fix in this case.

```
 oadm policy add-role-to-user basic-user openshift-dev --config=${OPENSHIFT_DIR}/admin.kubeconfig
 oadm policy add-role-to-user cluster-admin admin --config=${OPENSHIFT_DIR}/admin.kubeconfig
```

**Comment by hferentschik** [comment]
> Need to dig more to understand what is its privileges

Same here. I usually ssh into the box and use `oc --config=/var/lib/origin/openshift.local.config/master/admin.kubeconfig <command>`. I would have expected that the policy command would work, but it does not. So I guess we need to indeed dig a bit deeper.

**Comment by LalatenduMohanty** [comment]
@hferentschik as discussed , with the admin we should be able to run pretty much all oc commands and access to all namespaces

**Comment by praveenkumar** [comment]
@hferentschik looks like below snip solve it but have to include it with provision script and check if that work as expected.

```
# sudo oadm policy add-cluster-role-to-user cluster-admin admin --config=/var/lib/origin/openshift.local.config/master/admin.kubeconfig
# oc status
In project default on server https://localhost:8443

svc/docker-registry - 172.30.90.109:5000
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:v1.1.1 
    #1 deployed 4 minutes ago - 1 pod
  exposed by route/docker-registry on pod port 5000-tcp

svc/kubernetes - 172.30.0.1 ports 443, 53, 53

svc/router - 172.30.31.11 ports 80, 9101
  dc/router deploys: 
    docker.io/prom/haproxy-exporter:latest
    #1 deployed 4 minutes ago - 1 pod
    docker.io/openshift/origin-haproxy-router:v1.1.1
    #1 deployed 4 minutes ago - 1 pod

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
# oc get nodes
NAME          LABELS                               STATUS    AGE
centos7-adb   kubernetes.io/hostname=centos7-adb   Ready     4m
```

**Comment by hferentschik** [comment]
> looks like below snip solve it 

Which one? I am bit lost what you mean. Do you refer to:

```
sudo oadm policy add-cluster-role-to-user cluster-admin admin --config=/var/lib/origin/openshift.local.config/master/admin.kubeconfig
```

Is this not what you do already?

**Comment by hferentschik** [comment]
@praveenkumar not I got it. Found it now as well. It is _add-cluster-role-to-user_ instead of _add-role-to-user_. It works now for me. Let's update _openshift_provision_

**Comment by praveenkumar** [comment]
@hferentschik right :+1: , will send PR for same.

**Comment by hferentschik** [comment]
Nice. I'll test it, once I get hold of a new build :-)

**Comment by hferentschik** [comment]
I think we need to re-open this one. It is still not working. Without any additional provisioning the admin user still has not all privileges. Not sure why the _openshift_provision_ does not work.

When I add:

```
    export KUBECONFIG=/var/lib/openshift/openshift.local.config/master/admin.kubeconfig
    oadm policy add-cluster-role-to-user cluster-admin admin
```

to my _Vagrantfile_ things work fine. I can login as admin and have all privileges.

**Comment by hferentschik** [comment]
can we add focus:devex please
