### ISSUE TITLE
Unable to change OpenShift image defined  in /etc/sysconfig/openshift_option 

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-utils#34]
As part of the OpenShift service config we have;

```
ExecStartPre=-/usr/bin/docker tag ${DOCKER_REGISTRY}/${IMAGE} openshift
```

This won't work if the image is not pulled yet. This makes the `IMAGE` option in _/etc/sysconfig/openshift_option_ useless. One needs to pull the image first and then tag (in order to allow to run against a different OpenShift version).

Also in order to allow for example to run latest Origin, it does not make sense to prefix `DOCKER_REGISTRY`. The image should be given fully specified.

**Comment by hferentschik** [comment]
On that note, there are several `ExecStartPre` items now. Wouldn't it be better to collect them in a separate script as well?

**Comment by bexelbie** [comment]
@praveenkumar Can you shed some light on this?

**Comment by hferentschik** [comment]
_/etc/sysconfig/openshift_option _ (which should by the way be _/etc/sysconfig/openshift_ to align with the other files in this directory) offers an option to define the OpenShift image to run. In theory one should be able to change this image name (eg from 3.1 to 3.2) and use a different OpenShift image. 

Starting/stopping OpenShift is via starting the named container _openshift_. This naming/tagging is done in the ExecStartPre hook mentioned above. However, this only works if the image to tag is already pulled. In _openshift_vagrant_ we did a pull and tag. Here we only have a tag. This works, since the default OSE image is cached on the VM already. It will fail once I change the image in _openshift_option_. There is more needed to make this happen. Most likely at least one or more `ExecStartPre` lines in which cases one really should pull the whole thing into its own script.

**Comment by LalatenduMohanty** [comment]
In adb-utils code  I can see below  for openshift_option

```
# Modify these options if you want to change openshift route and hostname
OPTIONS="-host adb.vm -ip 10.1.2.2"
IMAGE="openshift/origin:v1.1.1"
DOCKER_REGISTRY="docker.io"
```

In CDK

```
# Modify these options if you want to change openshift route and hostname
OPTIONS="-host cdk.vm -ip 10.1.2.2"
IMAGE="openshift3/ose:v3.1.0.4"
DOCKER_REGISTRY="registry.access.redhat.com"
```

@praveenkumar Can't we make the two files same for both upstream and downstream with some extra logic ?

**Comment by LalatenduMohanty** [comment]
@hferentschik +1 to the idea of script then multiple ExecStartPre . It will make it more readable and maintainable . However it does look like a blocker for 2.0 GA

**Comment by hferentschik** [comment]
> However it does look like a blocker for 2.0 GA

Did you want to add a _not_ somewhere?

> +1 to the idea of script then multiple ExecStartPre 

The way I see it, using a different image via the options file (as intended by it) is not working and needs work. Personally I would in this case put things into a script. That might technically not be necessary, but seems to me the easiest option.

Personally this is a blocker for me or at least a major bug.

**Comment by hferentschik** [comment]
Not also, if the CDK ships with OSE 3.1 we would have a easy way for people here to upgrade to 3.2 once it is out. Provided it works.

**Comment by praveenkumar** [comment]
@hferentschik @LalatenduMohanty 
**CDK prospective:-**
Whole idea about caching specific tags of OSE docker images to make sure once user have CDK box it should not get any different tag images and with one release we will ship whatever public facing tag available for OSE. If OSE 3.2 is out in future then we should build our CDK box which updated cache images and update to access.redhat.com. We also have QE effort here to make sure whatever we include for a release is tested. 
`openshift3/ose:v3.1.0.4`  is used to create tag with `openshift` and not used to pull images (In case it create confusion).
https://github.com/projectatomic/adb-utils/blob/master/services/openshift/openshift.service#L14

**ADB prospective:-**
As long as we don't have image caching for box we are pulling images in Vagrantfile and remain part is same as what we target for CDK. 

> This works, since the default OSE image is cached on the VM already. It will fail once I change the image in >openshift_option. There is more needed to make this happen. Most likely at least one or more ExecStartPre >lines in which cases one really should pull the whole thing into its own script.

Do we really need it for script way because then User will file/create issues which we didn't ship in CDK box but since we are making it good for developer experience we can documents few steps if a developer want to run different tag images of openshift which we shipped in release version. Our cache version of openshift also go through some amount of QE.

**Comment by hferentschik** [comment]
> Whole idea about caching specific tags of OSE docker images to make sure once user have CDK box it should not get any different tag images and with one release we will ship whatever public facing tag available for OSE

Sure, but I think it would be nice if one could change the used image. This does not need to be supported. However, advanced users can use it to for example use the latest OSE or Origin image. This is what the tag field does in the openshift-vagrant setup. I do the latter a lot, since I need features which I cannot get in the old version of OSE.

> If OSE 3.2 is out in future then we should build our CDK box which updated cache images and update to access.redhat.com

Right, but this binds you to releases which might or might not happen.

> We also have QE effort here to make sure whatever we include for a release is tested. 

Sure, but there is a difference between what's tested and "supported" to what you can do.

> openshift3/ose:v3.1.0.4 is used to create tag with openshift and not used to pull images (In case it create confusion).

The confusion is that in _openshift_options_ there is a parameter _IMAGE_ which implies that I can define the OSE/Origin tag to be used. However, this is not possible. The whole mechanism is based around pre-cached images and only with these images the scripts will work. So, if you are not going to implement this, then at least the _IMAGE_ option should be removed. You might as well hard code it in this case. Personally, I would consider this a step back though.

> As long as we don't have image caching for box we are pulling images in Vagrantfile and remain part is same as what we target for CDK. 

If this mechanism is supposed to work, why would you require to pull the image from the _Vagrantfile_. That's makes no sense. It could trivially be handled by the service scripts. 

> but since we are making it good for developer experience we can documents few steps if a developer want to run different tag images of openshift which we shipped in release version.

exactly, we want a good user experience. The step should be just to change the option. Why require more and why make it more complicated?

**Comment by praveenkumar** [comment]
> The confusion is that in openshift_options there is a parameter IMAGE which implies that I can define the OSE/Origin tag to be used. However, this is not possible. The whole mechanism is based around pre-cached images and only with these images the scripts will work. So, if you are not going to implement this, then at least the IMAGE option should be removed. You might as well hard code it in this case. Personally, I would consider this a step back though.

For current release schedule I don't want to include some other steps/scripts (I will remove IMAGE option from options just to avoid any confusion). To handle this issue I will work on a separate branch and push changes there if everything look good then will merge it to master, hope that will make everyone happy :)

I will keep this bug open till we have required features but remove milestone from 2.0 GA

> exactly, we want a good user experience. The step should be just to change the option. Why require more and why make it more complicated?

Agreed, we don't want to make any complicated process to handle this issue.

**Comment by LalatenduMohanty** [comment]
@praveenkumar @bexelbie Can we close this issue now?

**Comment by praveenkumar** [comment]
@LalatenduMohanty let we keep it open and once we have latest ADB release which suppose to contain adb-utils-1.1 then we will ask @hferentschik to give it a try and close that issue.

**Comment by hferentschik** [comment]
Closing this issue, since it is resolved (at least in CDK)
