### ISSUE TITLE
Box IP hard coded in /etc/sysconfig/openshift_option

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/adb-utils#35]
Following are the contents of `/etc/sysconfig/openshift_option`

```
# /etc/sysconfig/openshift_options

# Modify these options if you want to change openshift route and hostname
OPTIONS="-host adb.vm -ip 10.1.2.2"
IMAGE="openshift/origin:v1.1.1"
DOCKER_REGISTRY="docker.io"
```

Box IP `10.1.2.2` is hard coded in this config.

External client connection to OpenShift server in the box will not work if box IP is different.

**Comment by praveenkumar** [comment]
@navidshaikh Currently this IP is only a place-holder not used in the scripts. The way we are using it in the script is getting IP of the box (https://github.com/projectatomic/adb-utils/blob/master/services/openshift/scripts/openshift#L13) and in case it fail then this hard-coded IP get used but again this we have to remove from `config-file`.

**Comment by navidshaikh** [comment]
@praveenkumar 

> in case it fail then this hard-coded IP get used but again this we have to remove from config-file.

This is error prone though, IMO if script can't find IP, script should fail with respective error.

**Comment by praveenkumar** [comment]
> This is error prone though, IMO if script can't find IP, script should fail with respective error. 

Yes it is, will do needful for this bug.
