### ISSUE TITLE
Provisioning script does "too much" for a general purpose OpenShift setup

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-utils#4]
_From @hferentschik on January 25, 2016 13:46_

`/opt/adb/openshift_provision` does some basic provisioning for OpenShift. It sets up the OpenShift registry as well as the router. However, it also does change the default permissions of OPenShift to allow to run any image. I think this goes too far. This should most likely be user driven.

The same applies for the imported templates and the created test-admin user. Both things are use-case specific and should be driven by user provisioning.

_Copied from original issue: projectatomic/adb-atomic-developer-bundle#214_

**Comment by praveenkumar** [comment]
_From @hferentschik on January 25, 2016 13:55_

Please add label focus:devex

**Comment by praveenkumar** [comment]
>  It also does change the default permissions of OPenShift to allow to run any image. I think this goes too far. This should most likely be user driven.

@hferentschik you mean that it change admin.kubeconfig permission here?

> The same applies for the imported templates and the created test-admin user. Both things are use-case specific and should be driven by user provisioning.

As per our discussion we will have atleast a test-user and one sample template may be `hello openshift` and other things can be user-case specific.

**Comment by hferentschik** [comment]
>  you mean that it change admin.kubeconfig permission here?

No, I was actually thinking of letting the user do it in the `Vagrantfile` during provisioning.

> As per our discussion we will have atleast a test-user and one sample template may be hello openshift and other things can be user-case specific.

I think this test-user and sample template should also be in the `Vagrantfile`. AFAIU, you guys ship with a `Vagrantfile` as well, which users than should use as a starting point for their work. I'll add it there. 

There are several reasons why I would create this separation:
- Create transparency. The user can actually see/learn how OpenShift is configured (compared to some script somewhere on the VM which might be hard to locate)
- The user can easily change OpenShift behavior by modifying the configuration (opposed to locating and modifying systemctl scripts)
- It allows support of multiple use cases. Users of the CDK might have different requirements for the OpenShift setup. They should be able to configure OpenShift w/o having to modify the service itself
- Externalizing the OpenShift config also decouples release cycles. One can for example easier upgrade to another version of OSE  

It comes really down to what the plan is for OpenShift on CDK? Is it a general purpose instance or is it supposed to just cater one single use case (ours)?

**Comment by praveenkumar** [comment]
> It comes really down to what the plan is for OpenShift on CDK? Is it a general purpose instance or is it supposed to just cater one single use case (ours)? 

It should be general purpose instance and then user can use it according to their requirements. Now whatever reasons you pointed out make sense but those we have to include it in documents somewhere.

**Comment by hferentschik** [comment]
Regarding the templates. No matter what and how templates are added, we cannot refer to templates pointing using URLs to master in some repository. Either we only used tagged versions or alternatively the CDK compiles its own template.

**Comment by LalatenduMohanty** [comment]
https://github.com/projectatomic/adb-utils/issues/13 tracks the template inclusion in to ADB/CDK
