### ISSUE TITLE
Origin Version hardcode 

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-utils#40]
Following are the contents of `/etc/sysconfig/openshift_option`

```
# /etc/sysconfig/openshift_options

# Modify these options if you want to change openshift route and hostname
OPTIONS="-host adb.vm -ip 10.1.2.2"
IMAGE="openshift/origin:v1.1.1"
DOCKER_REGISTRY="docker.io"
```

IMAGE should not be hardcoded

**Comment by praveenkumar** [comment]
@bexelbie It help us to use specific version of `origin` image instead of `latest`. It also helps us to track which version of origin shipped to specific ADB release. 

What you suggest? (Should be part of vagrant file?)

**Comment by LalatenduMohanty** [comment]
@praveenkumar I think your intention was to keep the OpenShift version stable through ADB. I think thats a good choice because OpenShift origin pushes images through nightly builds and there is high chance that it might break the setup. 

However we need to provide a simple way for users if he/she want to use the latest versions.

**Comment by praveenkumar** [comment]
@LalatenduMohanty yes, I will work on that bit also but my current intention is keep stable version of OpenShift through ADB releases.

**Comment by bexelbie** [comment]
I am all for stable version, but we need to make it super easy to change.

**Comment by praveenkumar** [comment]
Agreed, something what @hardy pointed out #34

**Comment by praveenkumar** [comment]
`sccli` make easy to pass different environment variable from Vagrantfile and update  systemd service environment file. So now hard-coded versions are by default and if user want to use different then pass required parameters to `sccli`
