### ISSUE TITLE
There is no service reload for OpenShift service

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-utils#5]
_From @hferentschik on January 25, 2016 13:37_

`$sudo systemctl reload openshift`
Failed to reload openshift.service: Job type reload is not applicable for unit openshift.service.

_Copied from original issue: projectatomic/adb-atomic-developer-bundle#213_

**Comment by praveenkumar** [comment]
_From @hferentschik on January 25, 2016 13:38_

Please add label focus:devex

**Comment by praveenkumar** [comment]
_From @hferentschik on January 25, 2016 13:55_

TBH, not sure whether it is really needed. Needs discussing.

**Comment by LalatenduMohanty** [comment]
We should provide `systemctl reload openshift` as we are providing the systemd service files. However this is not a priority unless @hferentschik has a specific usecase.

**Comment by hferentschik** [comment]
> However this is not a priority unless @hferentschik has a specific usecase.

No specific usecase. Just trying to arrive at a Systemd service which works as expected. But it seems that 'reload' is not really required indeed. Nice to have maybe.

**Comment by hferentschik** [comment]
We can even close this one. I don't think this is needed.

**Comment by praveenkumar** [comment]
This is not needed for openshift service case.
