### ISSUE TITLE
After "sccli openshift" , how do we expect the user to know openshift user information ?

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-utils#55]
We create two users in OpenSHift i.e. openshift-dev and admin . We should either print these username/password in the command line or add it to the documentation

**Comment by praveenkumar** [comment]
@bexelbie how about having both? We will add patch to sccli for providing information about openshift initially and also document it.

@LalatenduMohanty My understanding is that this will going to used by service-manager and then it will provide required info about openshift to user. Once we have that capability then we don't actually require to have this information on `sccli` side.

@navidshaikh Thoughts?

**Comment by bexelbie** [comment]
+1 for printing it and adding it to docs.  We need to keep this printed from sccli, imho because usage directly is valid.

**Comment by navidshaikh** [comment]
> My understanding is that this will going to used by service-manager and then it will provide required info about openshift to user.

Yes.

@praveenkumar : Is there a way we can get the configured user information from some APIs or config etc ?

**Comment by praveenkumar** [comment]
@navidshaikh  yes and we need to discuss it.

**Comment by LalatenduMohanty** [comment]
I think we have a better understanding now i.e. https://github.com/projectatomic/vagrant-service-manager/issues/163

I suggest `sccli` should print those info and vsm relays them to users during `vagrant up`

**Comment by navidshaikh** [comment]
Complete setup information text of OpenShift service should reside (and processed if needed) at one place and shown to user. +1 on the proposal

**Comment by brgnepal** [comment]
Probably [theses logs](https://gist.github.com/budhrg/553069ce583286836e444787091622ec#file-vup-sh-L11-L101) might be useful what is to be expected from `sccli`. 
`type` and `data` are two things which we get one executing command on remote machine through Vagrant.

**Comment by hferentschik** [comment]
I think documenting the defaults is fair enough. The problem with printing is that it can easily be wrong, for example if the user adds/changes logins. So unless we have a way to verify that the default credentials are still valid, I'd rather don't print anything.

**Comment by aweiteka** [comment]
From a vagrant up perspective on component centos-openshift-setup this seems done.

```
==> default: You can now access OpenShift console on: https://10.1.2.2:8443/console
==> default:
==> default: Configured basic user: openshift-dev, Password: devel
==> default:
==> default: Configured cluster admin user: admin, Password: admin
==> default:
==> default: To use OpenShift CLI, run:
==> default: $ vagrant ssh
==> default: $ oc login
==> default:
==> default: To browse the OpenShift API documentation, follow this link:
==> default: http://openshift3swagger-claytondev.rhcloud.com
==> default:
==> default: Then enter this URL:
==> default: https://10.1.2.2:8443/swaggerapi/oapi/v1
==> default: .
```

**Comment by brgnepal** [comment]
@praveenkumar This seems to be done and need to be closed as I believe we agreed on Vagrantfile approach till it is implemented in vagrant-service-manager https://github.com/projectatomic/vagrant-service-manager/issues/163

**Comment by praveenkumar** [comment]
@budhrg yes adding details is under scope of vagrant-service-manager or Vagrantfile not from `sccli` because it is going to used internally.

**Comment by brgnepal** [comment]
Closing this issue as it is being tracked in https://github.com/projectatomic/vagrant-service-manager/issues/163
