### ISSUE TITLE
Default project for openshift-dev user

### ISSUE THREAD

**Issue by mmalina** [projectatomic/adb-utils#76]
It would be nice to have some default project created for the openshift-dev user defined here:
https://github.com/projectatomic/adb-utils/blob/master/services/openshift/scripts/openshift#L113

When you start cdk in Eclipse/JBDS, a connection to openshift is created automatically in the OpenShift Explorer view. When you connect as the openshift-dev user, at the beginning you don't see anything under that connection which may seem like it's not working properly. So if there is a project to start with, it will be nicer for the user.

**Comment by praveenkumar** [comment]
@mmalina yes this can be done by adding below patch to after https://github.com/projectatomic/adb-utils/blob/master/services/openshift/scripts/openshift_provision#L122 

```
  oc login https://127.0.0.1:8443 -u openshift-dev -p devel \
        --certificate-authority=${OPENSHIFT_DIR}/ca.crt &>/dev/null
  oc new-project test --display-name="OpenShift 3 Sample" \
        --description="This is an example project to demonstrate OpenShift v3" &>/dev/null
```

**Comment by mmalina** [comment]
@praveenkumar ok, great, thanks. Let me know if you want a PR for that ;)

**Comment by praveenkumar** [comment]
@mmalina please go head and make your contribution :+1:

**Comment by mmalina** [comment]
@praveenkumar you made it way too easy for me :) but ok, here's the PR: https://github.com/projectatomic/adb-utils/pull/78

**Comment by praveenkumar** [comment]
#78 Fix it
