### ISSUE TITLE
openshift (oc) bash auto completion is missing

### ISSUE THREAD

**Issue by tnozicka** [projectatomic/adb-utils#85]
We should support oc auto completion which is currently not working.

``` bash
$ oc des<TAB>
$ oc describe
```

Openshift has such scripts: https://github.com/openshift/origin/tree/master/contrib/completions/bash

**Comment by hferentschik** [comment]
+1 I like that. That's a nice usability improvement.

**Comment by praveenkumar** [comment]
@tnozicka this should be enable for host or for the guest? My understanding is for a developer/user ADB is black-box and all required operation they do from host and this we can include in the docs (for Unix/Linux host).

**Comment by tnozicka** [comment]
@praveenkumar I would like to see it enabled for both. Although your understanding is right for most cases, it is useful to have it inside the box as well. Users might want to just try the box before starting or debug something. It is also good for us and others who are debugging something inside the box. 

Just add the file (~222K) to _/etc/bash_completion.d/_ and mention this in the user documentation as well:

``` bash
curl -G https://raw.githubusercontent.com/openshift/origin/master/contrib/completions/bash/oc > /etc/bash_completion.d/oc
```

We probably want to do this for _oadm_ and _openshift_ as well.

**Comment by hferentschik** [comment]
> this should be enable for host or for the guest? My understanding is for a developer/user ADB is black-box and all required operation they do from host

that's not true. Both use cases are valid. Driving from the host or the VM. The idea is for sure to push more towards easy use from the host, but everything should work on the VM as well. Being on Windows where one for example would not have the bash completions (unless running in a Cygwin shell), some users might prefer to ssh into the VM to benefit from the tab completion. 

 and this we can include in the docs (for Unix/Linux host).
