### ISSUE TITLE
Evaluate which imagestreams are required for ADB and CDK

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-utils#87]
We need to evaluate which imagestreams are required for ADB and CDK as upstream origin has two image streams i.e. 
1. One is CentOS and docker public registry based -> https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json
2. Another is RHEL based and uses registry.access.redhat.com -> https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-rhel7.json

Also for `eap64-mysql-persistent-s2i` application we need `jboss-eap64-openshift` image stream.

**Comment by LalatenduMohanty** [comment]
https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json has WildFly imagestreams which we should include in ADB and CDK.

**Comment by kadel** [comment]
https://github.com/jboss-openshift/application-templates/blob/master/jboss-image-streams.json
Please include this one again also.

It is required for all applications that are using `jboss-eap64-openshift`
