### ISSUE TITLE
Unified CLI for adb-utils and its scoped functions

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/adb-utils#92]
We are having multiple scripts for different use cases viz sccli, add_insecure_registry. IMO, we should think about having a single command line with commands and sub-commands which are scoped for utilities around containers / orchestrators / ADB / CDK. Thoughts?

How did it came? see context here https://github.com/projectatomic/adb-utils/pull/91

**Comment by praveenkumar** [comment]
Currently we are achieving this after modify `sccli` and it's behaving bridge for VSM and box.
